const path = require('path'); const express = require('express'); const helmet = require('helmet'); const cors = require('cors'); const rateLimit = require('express-rate-limit'); const bcrypt = require('bcryptjs'); const jwt = require('jsonwebtoken'); const Joi = require('joi');
const Product = require('./models/Product'); const User = require('./models/User'); const Order = require('./models/Order'); const auth = require('./middleware/auth'); const { sendOrderEmail } = require('./services/email');
const app = express(); app.set('trust proxy', 1); app.use(helmet({ contentSecurityPolicy: false })); app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(',') || true })); app.use(express.json({ limit: '5mb' })); app.use(rateLimit({ windowMs: 900000, limit: 300, standardHeaders: 'draft-7', legacyHeaders: false })); app.use(express.static(path.join(__dirname, '..', 'public')));
const sign = u => jwt.sign({ id: u._id, role: u.role, name: u.name }, process.env.JWT_SECRET, { expiresIn: '7d' });
const emailRule = Joi.string().trim().lowercase().email({ tlds: { allow: false } }).required();
const phoneRule = Joi.string().pattern(/^\+[1-9]\d{7,17}$/).message('Contact must include a valid country code and 6 to 14 phone digits').required();
app.use('/api/orders', (req,res,next) => {
  if (req.method !== 'POST') return next();
  const { error } = phoneRule.validate(req.body?.delivery?.contact);
  if (error) return res.status(400).json({ message: error.message });
  next();
});
const productImageRule = Joi.alternatives().try(
  Joi.string().uri(),
  Joi.string().pattern(/^file:\/\//i),
  Joi.string().pattern(/^data:image\/(png|jpe?g|webp|gif);base64,[A-Za-z0-9+/=\s]+$/i)
);
const productSchema = Joi.object({ name: Joi.string().min(2).max(140).required(), description: Joi.string().max(2000).required(), category: Joi.string().required(), price: Joi.number().min(0).required(), stock: Joi.number().integer().min(0).required(), imageURL: productImageRule.required(), images: Joi.array().items(productImageRule).max(6).default([]) });
app.get('/health', (_, res) => res.json({ ok: true }));
app.post('/api/auth/register', async (req,res,next) => { try { const v = await Joi.object({ name:Joi.string().min(2).required(), email:emailRule, password:Joi.string().min(8).required(), role:Joi.string().valid('buyer','seller','admin').default('buyer') }).validateAsync(req.body); if (await User.exists({email:v.email})) return res.status(409).json({message:'Email already registered'}); const user=await User.create({...v,password:await bcrypt.hash(v.password,12)}); res.status(201).json({token:sign(user),user:{id:user._id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e)} });
app.post('/api/auth/login', async (req,res,next) => { try { const v=await Joi.object({email:emailRule,password:Joi.string().required()}).validateAsync(req.body); const user=await User.findOne({email:v.email}).select('+password'); if(!user||!(await bcrypt.compare(v.password,user.password))) return res.status(401).json({message:'Invalid email or password'}); res.json({token:sign(user),user:{id:user._id,name:user.name,email:user.email,role:user.role}}); } catch(e){next(e)} });
app.get('/api/products',async(req,res,next)=>{try{res.json(await Product.find(req.query.category?{category:req.query.category}:{}).sort('-createdAt').limit(100))}catch(e){next(e)}}); app.get('/api/products/:id',async(req,res,next)=>{try{const p=await Product.findById(req.params.id);if(!p)return res.status(404).json({message:'Product not found'});res.json(p)}catch(e){next(e)}});
app.post('/api/products',auth('seller'),async(req,res,next)=>{try{res.status(201).json(await Product.create({...(await productSchema.validateAsync(req.body)),seller:req.user.id}))}catch(e){next(e)}}); app.patch('/api/products/:id',auth('seller'),async(req,res,next)=>{try{const p=await Product.findOneAndUpdate({_id:req.params.id,seller:req.user.id},await productSchema.fork(['name','description','category','price','stock','imageURL','images'],s=>s.optional()).validateAsync(req.body),{new:true});if(!p)return res.status(404).json({message:'Product not found'});res.json(p)}catch(e){next(e)}}); app.delete('/api/products/:id',auth('seller'),async(req,res,next)=>{try{const p=await Product.findOneAndDelete({_id:req.params.id,seller:req.user.id});if(!p)return res.status(404).json({message:'Product not found'});res.status(204).end()}catch(e){next(e)}}); app.get('/api/seller/products',auth('seller'),async(req,res,next)=>{try{res.json(await Product.find({seller:req.user.id}).sort('-createdAt'))}catch(e){next(e)}});
app.post('/api/orders',auth(),async(req,res,next)=>{try{const v=await Joi.object({items:Joi.array().items(Joi.object({productId:Joi.string().required(),quantity:Joi.number().integer().min(1).max(20).required()})).min(1).required(),delivery:Joi.object({address:Joi.string().min(10).required(),contact:Joi.string().min(7).required()}).required(),paymentResult:Joi.string().valid('success','failure').default('success')}).validateAsync(req.body);if(v.paymentResult==='failure')return res.status(402).json({message:'Dummy payment declined. Try again.'});const products=await Product.find({_id:{$in:v.items.map(i=>i.productId)}}).populate('seller');if(products.length!==v.items.length)return res.status(400).json({message:'One or more products are unavailable'});const map=new Map(products.map(p=>[String(p._id),p]));const items=v.items.map(i=>{const p=map.get(i.productId);if(p.stock<i.quantity)throw Object.assign(new Error(`${p.name} is out of stock`),{status:409});return {product:p._id,name:p.name,price:p.price,quantity:i.quantity,imageURL:p.imageURL}});await Promise.all(v.items.map(i=>Product.updateOne({_id:i.productId},{$inc:{stock:-i.quantity}})));const order=await Order.create({buyer:req.user.id,items,total:items.reduce((s,i)=>s+i.price*i.quantity,0),delivery:{...v.delivery,eta:'3–5 business days'}});const buyer=await User.findById(req.user.id);sendOrderEmail({buyer,order,sellerEmail:products[0].seller?.email}).catch(()=>{});res.status(201).json(order)}catch(e){next(e)}}); app.get('/api/orders',auth(),async(req,res,next)=>{try{res.json(await Order.find({buyer:req.user.id}).sort('-createdAt'))}catch(e){next(e)}}); app.patch('/api/orders/:id/cancel',auth(),async(req,res,next)=>{try{const order=await Order.findById(req.params.id);if(!order)return res.status(404).json({message:'Order not found'});if(String(order.buyer)!==String(req.user.id))return res.status(403).json({message:'You do not own this order'});if(['cancelled','delivered'].includes(order.status))return res.status(400).json({message:`Order cannot be cancelled from ${order.status} status`});for(const item of order.items){if(item.product){await Product.updateOne({_id:item.product},{$inc:{stock:item.quantity}})}}order.status='cancelled';await order.save();res.json(order)}catch(e){next(e)}});
app.use((err,req,res,next)=>res.status(err.isJoi?400:err.status||500).json({message:err.isJoi?err.details[0].message:err.message||'Internal server error'})); module.exports=app;
